### ISSUE TITLE
Improper Indentation

### ISSUE THREAD

**Issue by ManishAswal12345** [YuvrajJoshi/Genetic-Task-Scheduling-in-Cloud-using-CloudSim#1]
As the title suggests, indentation is not proper. Too much space is present at some areas.

**Comment by YuvrajJoshi** [comment]
Fixing it soon. Thank you.

**Comment by ManishAswal12345** [comment]
Can i do it for you? or you already did it?

**Comment by YuvrajJoshi** [comment]
I have fixed most of the class files. You can fix the GeneticAlgorithm.java
file.

**Comment by ManishAswal12345** [comment]
ok thanks
